knpu_oauth2_client:
    # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
    clients:
        yandex_main:
            # this will be one of the supported types
            type: yandex
            client_id: '%env(OAUTH_YANDEX_ID)%'
            client_secret: '%env(OAUTH_YANDEX_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_yandex_check
            redirect_params: { }
#            graph_api_version: v2.12
