version: "3.7"
services:
  app:
    build:
      args:
        user: zdreamer
        uid: 1000
      context: ./
      dockerfile: docker-compose/app/Dockerfile
    image: rss-reader
    container_name: my-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - rss-reader

  nginx:
    image: nginx:alpine
    container_name: my-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - rss-reader

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-compose/postgre/init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - rss-reader

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: zzzahar@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    networks:
      - rss-reader

  jetbrains:
    build:
      args:
        user: jetbrains
        uid: 1000
      context: ./
      dockerfile: docker-compose/jetbrains/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3022:22"
      - "5990:5990"
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - jetbrains-home:/home/jetbrains
    networks:
      - rss-reader

volumes:
  db-data:
    driver: local
  pgadmin-data:
    driver: local
  jetbrains-home:
    driver: local

networks:
  rss-reader:
    driver: bridge
