version: "3.7"
services:
  app:
    build:
      args:
        user: zdreamer
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: rss-reader
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - rss-reader

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - rss-reader

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./docker-compose/postgre/data:/var/lib/postgresql/data
      - ./docker-compose/postgre/init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - rss-reader

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - rss-reader

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 5050:80
    volumes:
      - ./docker-compose/pgadmin/data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: zzzahar@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    networks:
      - rss-reader

networks:
  rss-reader:
    driver: bridge
